In [23]:
from utils.config import get_settings
from trade.broker import BrokerSession
import MetaTrader5 as mt5
import pandas as pd
import numpy as np
login_settings = get_settings("settings/demo/login.json")
trading_settings = get_settings("settings/demo/trading.json")

mt5_login_settings = login_settings["mt5_login"]

session = BrokerSession()
symbol = "EURUSD"

# Start MT5
session.start_session(mt5_login_settings)
session.enable_symbols([symbol])


In [2]:
from talib import EMA, get_unstable_period, set_unstable_period, ADX, get_functions, abstract
from trade.indicators import get_stable_min_bars

In [3]:
x = session.get_candles(symbol, "H1", 100 )

In [18]:
get_unstable_period("EMA")

0

In [2]:
max(s for s in [])

ValueError: max() arg is an empty sequence

In [48]:
bars = get_stable_min_bars("EMA", 2)
set_unstable_period("EMA", bars - 2 + 1)
ema1 = EMA(x.close, 2)

In [20]:
set_unstable_period("EMA", 0)
ema2 = EMA(x.close, 10)

In [25]:
ema2[ema2 == np.nan]

array([], dtype=float64)

In [42]:
ema2[np.isnan(ema2)].size

9

In [49]:
ema1[np.isnan(ema1)].size

16

In [234]:
abstract.Function("EMA").function_flags

['Output scale same as input', 'Function has an unstable period']

In [43]:
a = avg_stable_windows[:14]
b = avg_stable_windows[14:]

In [48]:
max_bars = 1000
close = np.random.rand(max_bars) * 50
high = close + np.random.rand(max_bars) * 5
low = close - np.random.rand(max_bars) * 5
w = 100
off = 2 * w + 12

In [300]:
r = ((138.2* np.arange(2, 100) -155.55)**(1/1.53) - a.values).astype(int)
print(np.mean(r), r)

0.01020408163265306 [-1  0  1  2  2  3  2  2  3  1  2  1  2  0  3  0  0  0 -1  1  0  1  0  1
 -1  2  0 -1 -1  0  0  0 -5  0 -2 -3 -2  1 -2 -1  0 -2  0  1 -1  2  0 -4
 -3  2 -5 -2  2  3  0 -3 -1 -2  2  5  1 -1  0  2  3 -7 -4  0 -2 -4 -8 -7
  5  4 -1  1  1  5  2 -6  1  3  1  3  0  1 -2 -1  4  0  1  2 -7 -3  4  0
  1  5]


In [67]:
np.sqrt(840 - 1400)

C:\Users\grung\AppData\Local\Temp\ipykernel_4828\3369202441.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(840 - 1400)


nan

In [457]:

EMA(a.values, 2)

array([         nan,  25.5       ,  35.83333333,  45.94444444,
        55.31481481,  63.77160494,  72.59053498,  80.86351166,
        87.62117055,  95.87372352, 103.29124117, 110.43041372,
       118.14347124, 124.71449041, 132.23816347, 138.74605449,
       144.9153515 , 151.6384505 , 157.8794835 , 163.95982783,
       170.31994261, 176.43998087, 183.47999362, 188.49333121,
       193.49777707, 198.83259236, 203.61086412, 210.53695471,
       215.51231824, 221.83743941, 226.6124798 , 232.8708266 ,
       235.62360887, 240.54120296, 246.18040099, 252.72680033,
       259.57560011, 264.52520004, 267.50840001, 273.16946667,
       276.05648889, 279.35216296, 284.45072099, 290.15024033,
       295.38341344, 299.46113781, 303.82037927, 308.94012642,
       312.98004214, 317.32668071, 321.77556024, 323.92518675,
       329.97506225, 335.99168742, 336.66389581, 339.88796527,
       343.96265509, 347.9875517 , 354.66251723, 363.22083908,
       365.07361303, 366.35787101, 371.11929034, 376.03

In [143]:
p = Series(np.sqrt(fit[0] * np.arange(0, 100) + fit[1]))

C:\Users\grung\AppData\Local\Temp\ipykernel_10624\4084488277.py:1: RuntimeWarning: invalid value encountered in sqrt
  p = Series(np.sqrt(fit[0] * np.arange(0, 100) + fit[1]))


In [94]:
a

0      17.0
1      25.0
2      33.0
3      40.0
4      47.0
      ...  
93    276.0
94    277.5
95    277.5
96    280.0
97    282.0
Length: 98, dtype: float64

In [66]:
arr = np.random.rand(2000) * 50 # fake if highly volatile price data
func_ema_val = ta.func.RSI(arr, 14)[-1]
stream_ema_val = ta.func.RSI(arr[-i:], timeperiod)[-1]

NameError: name 'i' is not defined

In [15]:
from talib.abstract import EMA
if 'Function has an unstable period' in EMA.function_flags:
    print('unstable')

unstable


In [16]:
EMA.function_flags

['Output scale same as input', 'Function has an unstable period']

In [14]:
get_unstable_period("RSI")

0

In [7]:
dir(EMA)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__wrapped__']

In [6]:
EMA(EMA(np.random.random(20), 2) - 1, 2)

array([        nan,         nan, -0.75203802, -0.72308569, -0.46116107,
       -0.63651406, -0.57410872, -0.46475001, -0.5626544 , -0.60439485,
       -0.39232665, -0.54362966, -0.55125148, -0.35222303, -0.55460951,
       -0.4431824 , -0.37182995, -0.35094486, -0.48240554, -0.64306907])

In [12]:
from trade.indicators import RSIIndicator
c = session.get_candles(symbol, "M1", 14, 0, as_dataframe=True)
RSIIndicator(c.close).rsi()

time
1681365780    13.72549
1681365840    13.72549
1681365900    13.72549
1681365960    13.72549
1681366020    13.72549
1681366080    13.72549
1681366140    13.72549
1681366200    13.72549
1681366260    13.72549
1681366320    13.72549
1681366380    13.72549
1681366440    13.72549
1681366500    13.72549
1681366560    13.72549
Name: rsi, dtype: float64

In [28]:
p = np.array([20,11.25,12.35,14.5,18.45,12.75,15.35,13.05,16.10,12.20,11.65,13.25,15.30,14.85,16.15,19.05,21.45,17.55])[::-1]
RSI(p)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 45.83901774,
       43.115191  , 41.74833658, 54.18941067])

In [2]:
from trade.strategies import MovingAverageStrategy
mav = MovingAverageStrategy(5, 200)


In [24]:
import numpy as np
import timeit

arr = np.arange(1000000)


def append_value(arr):
    return np.append(arr, 1000000)


def concatenate_value(arr):
    return np.concatenate([arr, [1000000]])


print(timeit.timeit(lambda: append_value(arr), number=10000))
# Output: 10.277582999999988

print(timeit.timeit(lambda: concatenate_value(arr), number=10000))
# Output: 5.141081399999996


11.846058800000037
11.345299699999941


In [25]:
%%timeit
np.append(arr, 1000000)


1.19 ms ± 80.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
%%timeit
np.concatenate([arr, [1000000]])


1.18 ms ± 71.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
symbols = mt5.symbols_get()

In [9]:
b = -1
for s in symbols:
    si = mt5.symbol_info(s.name)
    a = si.volume_min
    if a != b:
        print(s.path, a, si.volume_step)
        b = a

Forex\Majors\EURUSD 0.01 0.01
Indices\Indices Spot\Major Spot Indices\AUS200 0.1 0.1
Indices\Indices Spot\Major Spot Indices\JP225 1.0 1.0
Indices\Indices Spot\Major Spot Indices\UK100 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\US2000 1.0 1.0
Indices\Indices Spot\Major Spot Indices\US30 0.1 0.1
Commodities\Metals\XAGEUR 0.01 0.01
Commodities\Energies\Energies Spot\XBRUSD 0.5 0.5
Crypto\BTCUSD 0.01 0.01
Crypto\LTCUSD 0.05 0.01
Crypto\DSHUSD 1.0 0.01
Stock CFD's\Nasdaq\AAPL.NAS 0.1 0.1
Crypto\XRPUSD 1.0 0.01
Crypto\XLMUSD 1000.0 100.0
Crypto\EOSUSD 1.0 0.01
Stock CFD's\NYSE\ETF\DBA.NYSE 0.1 0.1
Commodities\Metals\XAUAUD 0.01 0.01
Stock CFD's\NYSE\LIN.NYSE 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\CA60 1.0 1.0
Stock CFD's\Nasdaq\AMD.NAS 0.1 0.1
Crypto\ADAUSD 1.0 0.01
Stock CFD's\Nasdaq\HOOD.NAS 0.1 0.1
Crypto\XTZUSD 1.0 0.01
Crypto\BNBUSD 0.01 0.01
Indices\Indices Spot\Major Spot Indices\DE40 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\MidDE50 1.0 1.0
Stock CFD's\NYSE\PANW.

In [17]:
q = 1.00000
len(str(q)) - str(q).index(".") -1

1

In [29]:
%%timeit
pd.DataFrame(a)

356 µs ± 26 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [79]:
#%%timeit
session.get_candles("EURUSD", "M1", 1)

rec.array([(1679875440, 1.07721, 1.07721, 1.07721, 1.07721, 1, 33, 0)],
          dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [3]:
session.calculate_sltp("EURUSD", "buy", 1.0000, 10, 2)


(0.999, 1.002)

In [20]:
session.calculate_sltp("EURUSD", "buy", 1.08946, 10, 2)

AccountInfo(login=51136661, trade_mode=0, leverage=500, limit_orders=200, margin_so_mode=0, trade_allowed=True, trade_expert=True, margin_mode=2, currency_digits=2, fifo_close=False, balance=420.11, credit=0.0, profit=0.0, equity=420.11, margin=0.0, margin_free=420.11, margin_level=0.0, margin_so_call=100.0, margin_so_so=50.0, margin_initial=0.0, margin_maintenance=0.0, assets=0.0, liabilities=0.0, commission_blocked=0.0, name='Reyes Vega Leonardo Moises', server='ICMarketsSC-Demo', currency='GBP', company='Raw Trading Ltd')

In [26]:
symbols = mt5.symbols_get()

In [29]:
symbols[0]

SymbolInfo(custom=False, chart_mode=0, select=True, visible=True, session_deals=0, session_buy_orders=0, session_sell_orders=0, volume=0, volumehigh=0, volumelow=0, time=1679551157, digits=5, spread=0, spread_float=True, ticks_bookdepth=10, trade_calc_mode=0, trade_mode=4, start_time=0, expiration_time=0, trade_stops_level=0, trade_freeze_level=0, trade_exemode=2, swap_mode=1, swap_rollover3days=3, margin_hedged_use_leg=False, expiration_mode=15, filling_mode=2, order_mode=127, order_gtc_mode=0, option_mode=0, option_right=0, bid=1.08952, bidhigh=1.0899, bidlow=1.08555, ask=1.08952, askhigh=1.0899, asklow=1.08561, last=0.0, lasthigh=0.0, lastlow=0.0, volume_real=0.0, volumehigh_real=0.0, volumelow_real=0.0, option_strike=0.0, point=1e-05, trade_tick_value=0.8120969968653058, trade_tick_value_profit=0.8120969968653058, trade_tick_value_loss=0.812123377783553, trade_tick_size=1e-05, trade_contract_size=100000.0, trade_accrued_interest=0.0, trade_face_value=0.0, trade_liquidity_rate=0.0, 

In [2]:
session.calculate_sltp_2("EURUSD", "sell", price=1.09133, lot_size=0.05, risk_pct=0.01, rr_ratio=2)


409.3 1.2323


(1.092360597136, 1.089268805728)

In [80]:
si = mt5.symbol_info("GBPUSD")
si2 = mt5.symbol_info_tick("GBPUSD")
t = session.get_candles("GBPUSD", "M1", 1)
t2 = session.get_ticks("GBPUSD", 5)

In [81]:
t2.ask

array([1.22351, 1.22362, 1.22362, 1.22354, 1.22354])

In [67]:
si.bid

1.22295

In [62]:
si2

Tick(time=1679702218, bid=1.22295, ask=1.22323, last=0.0, volume=0, time_msc=1679702218646, flags=6, volume_real=0.0)

In [3]:
pd.DataFrame(mt5.copy_rates_from_pos("GBPUSD", mt5.TIMEFRAME_H1, 0, 1))


time     open     high      low    close  tick_volume  spread  \
0  1679565600  1.23238  1.23256  1.23164  1.23229          737       0   

   real_volume  
0            0

In [7]:
#%%timeit
a = mt5.copy_rates_from_pos("GBPUSD", mt5.TIMEFRAME_M1, 0, 1)
b = a.view(np.recarray)


61.9 µs ± 2.33 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [26]:
a = mt5.positions_get(symbol="EURUSD")


In [28]:
a[0].symbol

'EURUSD'

In [20]:
not 100

False

In [101]:
session.create_order()
mt5.orders_get(symbol="GBPUSD")


(TradeOrder(ticket=359065032, time_setup=1679875486, time_setup_msc=1679875486789, time_done=0, time_done_msc=0, time_expiration=0, type=2, type_time=0, type_filling=2, state=1, magic=0, position_id=0, position_by_id=0, reason=0, volume_initial=0.05, volume_current=0.05, price_open=1.18674, sl=0.0, tp=0.0, price_current=1.22426, price_stoplimit=0.0, symbol='GBPUSD', comment='', external_id=''),)

In [5]:
from enum import Enum
import MetaTrader5 as mt5
class TimeFrames(Enum):
    M1 = mt5.TIMEFRAME_M1
    M2 = mt5.TIMEFRAME_M2
    M3 = mt5.TIMEFRAME_M3
    M4 = mt5.TIMEFRAME_M4
    M5 = mt5.TIMEFRAME_M5
    M6 = mt5.TIMEFRAME_M6
    M10 = mt5.TIMEFRAME_M10
    M12 = mt5.TIMEFRAME_M12
    M15 = mt5.TIMEFRAME_M15
    M20 = mt5.TIMEFRAME_M20
    M30 = mt5.TIMEFRAME_M30
    H1 = mt5.TIMEFRAME_H1
    H2 = mt5.TIMEFRAME_H2
    H3 = mt5.TIMEFRAME_H3
    H4 = mt5.TIMEFRAME_H4
    H6 = mt5.TIMEFRAME_H6
    H8 = mt5.TIMEFRAME_H8
    H12 = mt5.TIMEFRAME_H12
    D1 = mt5.TIMEFRAME_D1
    W1 = mt5.TIMEFRAME_W1
    MN1 = mt5.TIMEFRAME_MN1


In [9]:
TimeFrames._member_names_


['M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M10',
 'M12',
 'M15',
 'M20',
 'M30',
 'H1',
 'H2',
 'H3',
 'H4',
 'H6',
 'H8',
 'H12',
 'D1',
 'W1',
 'MN1']

In [18]:
TimeFrames.D1.name

'D1'

In [17]:
A._member_names_

[]

In [44]:
mt5.symbols_get("BCH")[0].name

'BCHUSD'

In [59]:
mt5.symbol_select("USDTRY", True)

True

In [55]:
import numpy as np

o = np.arange(5).reshape(-1, 1)
u = np.arange(5).reshape(-1, 1)


In [57]:
np.append(o, u, axis=1)# .astype([("c", "<f8"), ("d", "<f8")])

array([[(0., 0.), (0., 0.)],
       [(1., 1.), (1., 1.)],
       [(2., 2.), (2., 2.)],
       [(3., 3.), (3., 3.)],
       [(4., 4.), (4., 4.)]], dtype=[('c', '<f8'), ('d', '<f8')])

In [12]:
d = np.diff(o)

In [58]:
import numpy as np

# Create two 1D numpy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Define the field names and data types for the recarray
field_names = ['field1', 'field2']
data_types = ['int', 'int']

# Use the `numpy.rec.fromarrays` function to create the 2D recarray
recarr = np.rec.fromarrays([arr1, arr2], names=field_names, formats=data_types)

# Print the recarray
print(recarr)


[(1, 4) (2, 5) (3, 6)]


In [63]:
recarr.field1

array([1, 2, 3])

In [64]:
def get_unstable_indicators():
    unstable_indicators = []
    for ind_name in get_all_indicators():
        flags = Function(ind_name).function_flags
        # print(flags)
        if flags is not None and 'Output scale same as input' in flags:
            unstable_indicators.append(ind_name)
    return unstable_indicators

In [66]:
a = get_unstable_indicators()
a

['MAX',
 'MIN',
 'MINMAX',
 'BBANDS',
 'DEMA',
 'EMA',
 'HT_TRENDLINE',
 'KAMA',
 'MA',
 'MAMA',
 'MAVP',
 'MIDPOINT',
 'MIDPRICE',
 'SAR',
 'SAREXT',
 'SMA',
 'T3',
 'TEMA',
 'TRIMA',
 'WMA',
 'AVGPRICE',
 'MEDPRICE',
 'TYPPRICE',
 'WCLPRICE',
 'LINEARREG',
 'LINEARREG_INTERCEPT',
 'TSF']

In [ ]:
a

In [29]:
a = np.array([[1,]], dtype=("c", "<f8"))
a = a.view(np.recarray)

ValueError: mismatch in size of old and new data-descriptor

In [33]:
c = session.get_candles(symbol, "M1", 3)
d = session.get_candles(symbol, "M1", 1)


In [37]:
e = np.append(c, d)

In [41]:
np.delete(e, np.s_[:2], axis=0).view(np.recarray)


rec.array([(1681360740, 1.09974, 1.0999, 1.09974, 1.0999, 10, 0, 0),
           (1681360740, 1.09974, 1.0999, 1.09974, 1.0999, 10, 0, 0)],
          dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [21]:
from yfinance import download, set_tz_cache_location, Tickers
from datetime import datetime as dt
import pytz

tz = pytz.timezone("US/Central")
# set_tz_cache_location(tz)
start = tz.localize(dt(2023, 4, 1))
end = tz.localize(dt.today())

data = download("EURUSD=X", start, end, interval="1h", auto_adjust=True)

[*********************100%***********************]  1 of 1 completed


In [40]:
data.rename(columns={C:C.lower() for C in data.columns}, inplace=True)

In [32]:
{"Datetime": "time", **{C:C.lower() for C in data.columns}}

{'Datetime': 'time',
 'Open': 'open',
 'High': 'high',
 'Low': 'low',
 'Close': 'close',
 'Volume': 'volume'}

In [36]:
data.rename({"Open": "open"})

IndexError: too many indices for array

In [7]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer



ct = ColumnTransformer(
    [
        #("norm1", Normalizer(norm='l1'), [0, 1]),
        ("norm2", Normalizer(norm='l1'), slice(2, 4))
    ]
)
X = np.array([[0., 1., 2., 2.],
              [1., 1., 0., 1.]])

# Normalizer scales each row of X to unit norm. A separate scaling
# is applied for the two first and two last elements of each
# row independently.
Y = ct.fit_transform(X)


In [9]:
Y.dtype.names = ("col1", "col2")#[("col1", "<f8"), ("col1", "<f8")]


ValueError: there are no fields defined

In [6]:
X.dtype.names

In [114]:
import numpy as np

# Create a 2D numpy array
arr = np.array([[1, 2], [3, 4]])

# Define the field names and data types for the recarray
field_names = ['field1', 'field2']
data_types = ['int', 'int']

# Use the `numpy.view` function to create the recarray
recarr = arr.view(dtype={'names': field_names, 'formats': data_types})

# Print the recarray
print(recarr)


[[(1, 2)]
 [(3, 4)]]


In [117]:
rarray = recarr.view(np.recarray)

In [128]:
rarray

rec.array([[(1, 2)],
           [(3, 4)]],
          dtype=[('field1', '<i8'), ('field2', '<i8')])

In [123]:
for i in rarray.dtype:
    print(i)

TypeError: 'numpy.dtype[void]' object is not iterable

In [31]:
recarray = recarr.view(np.recarray)

In [129]:
arr

array([[1, 2],
       [3, 4]])

In [24]:
arr = np.array([[1, 2, 3], [3, 4, 5]])


In [25]:
arr.astype(recarr.dtype).view

array([[(1, 1), (2, 2), (3, 3)],
       [(3, 3), (4, 4), (5, 5)]],
      dtype=[('field1', '<i8'), ('field2', '<i8')])

In [30]:
recarr.field1

AttributeError: 'numpy.ndarray' object has no attribute 'field1'

In [18]:
recarr[0].field1

AttributeError: 'numpy.ndarray' object has no attribute 'field1'

In [43]:
recarray[["field1", "field2"]].field2.astype(recarr.dtype)

array([[(2, 2)],
       [(4, 4)]], dtype=[('field1', '<i8'), ('field2', '<i8')])

In [42]:
recarray.field1.astype(name)

array([[1],
       [3]])

In [48]:
a = recarray.dtype

In [51]:
a.names[0]

'field1'

In [60]:
a.metadata

In [63]:
recarray.field1.dypes.names = [("field2", "<f8")]

AttributeError: 'numpy.ndarray' object has no attribute 'dypes'

In [64]:
a = recarray.field1

In [68]:
a.view(dtype={'names': ["a"], 'formats': ['<f8']})

array([[(4.9e-324,)],
       [(1.5e-323,)]], dtype=[('a', '<f8')])

In [69]:
a

array([[1],
       [3]])

In [76]:
c = np.rec.fromrecords(a, names="c")

In [85]:
np.recfunctions.merge_arrays((b, c), flatten=True)


AttributeError: module 'numpy' has no attribute 'recfunctions'

In [88]:
fields = np.hstack((b['a'], c['c']))

# Create a new recarray from the concatenated fields using fromarrays
recarr = np.core.records.fromarrays(fields.reshape(-1, 2).T, names='a,b')


In [98]:
np.append(b, c, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [105]:
c[["c"]]

rec.array([(1,), (3,)],
          dtype=[('c', '<i8')])

In [103]:
b.a

array([1, 3])

In [109]:
np.column_stack((b.a, c.c))

array([[1, 1],
       [3, 3]])

In [112]:
np.rec.fromarrays((b, c))

rec.array([((1,), (1,)), ((3,), (3,))],
          dtype=[('f0', (numpy.record, [('a', '<i8')])), ('f1', (numpy.record, [('c', '<i8')]))])

In [130]:
import numpy as np

# Define the input recarray and array to append
arr1 = np.rec.array([[(1, 2)], [(3, 4)]], dtype=[('field1', '<i8'), ('field2', '<i8')])
arr2 = np.array([[3], [3]])

# Append the new array as a new field to the input recarray
result = np.lib.recfunctions.append_fields(arr1, 'field3', arr2)

# Print the concatenated recarray
print(result)

AttributeError: module 'numpy.lib' has no attribute 'recfunctions'

In [131]:
import numpy as np

# Define the input recarray and array to append
arr1 = np.rec.array([[(1, 2)], [(3, 4)]], dtype=[('field1', '<i8'), ('field2', '<i8')])
arr2 = np.array([[3], [3]])

# Create a new recarray with the additional field
new_arr = np.core.records.fromarrays([arr1['field1'], arr1['field2'], arr2.T[0]], names='field1,field2,field3')

# Print the concatenated recarray
print(new_arr)

ValueError: array-shape mismatch in array 2 ("field3")

In [147]:
%%timeit
import numpy as np

# Create a recarray
arr = np.rec.array([(1, 2), (3, 4)], dtype=[('field1', '<i8'), ('field2', '<i8')])

# Create a 2D array to append
new_array = np.array([[5], [6]])
new_array = np.array([5, 6])

# Create a new recarray with an additional field
new_dtype = arr.dtype.descr + [('field3', '<i8')]
new_arr = np.empty(arr.shape, dtype=new_dtype)
for name in arr.dtype.names:
    new_arr[name] = arr[name]
new_arr['field3'] = new_array

# Print the new recarray
# print(new_arr)


19.3 µs ± 1.76 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [148]:
new_arr.view(np.recarray)

rec.array([(1, 2, 5), (3, 4, 6)],
          dtype=[('field1', '<i8'), ('field2', '<i8'), ('field3', '<i8')])

In [135]:
import numpy as np
from numpy.lib.recfunctions import append_fields

# Create a recarray
arr = np.rec.array([(1, 2), (3, 4)], dtype=[('field1', '<i8'), ('field2', '<i8')])

# Create a 2D array to append
new_arr = np.array([[5], [6]])

# Append the new field
new_dtype = arr.dtype.descr + [('field3', '<i8')]
new_arr = append_fields(arr, 'field3', new_arr, usemask=False, asrecarray=True)

# Print the new recarray
print(new_arr)


ValueError: could not broadcast input array from shape (2,1) into shape (2,)

In [155]:
np.arange(1, 10).reshape(-1,1)[:, 0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
new_arr["field4"] = np.array([8, 9])

ValueError: no field of name field4

In [160]:
new_arr.

array([(1, 2, 8), (3, 4, 9)],
      dtype=[('field1', '<i8'), ('field2', '<i8'), ('field3', '<i8')])

In [173]:
np.empty((2, 1), dtype=[('field1', '<i8'), ('field2', '<i8'), ('field3', '<i8')])

array([[(0, 0, 0)],
       [(0, 0, 0)]],
      dtype=[('field1', '<i8'), ('field2', '<i8'), ('field3', '<i8')])

In [189]:
from numpy import empty, recarray

def concat_recarrays(
    arr1: recarray, 
    arr2: recarray, 
) -> recarray:

    # Create a new recarray with an additional field
    out_dtypes = arr1.dtype.descr + arr2.dtype.descr #new_dtypes #[('field3', '<i8')]
    new_arr = empty(arr1.shape, dtype=out_dtypes)
    for name in arr1.dtype.names:
        new_arr[name] = arr1[name]
    for name in arr2.dtype.names:
        new_arr[name] = arr2[name]

    return new_arr.view(recarray)

In [186]:
arr1 = np.rec.array([(1, 2), (3, 4)], dtype=[('a', '<i8'), ('b', '<i8')])
arr2 = np.rec.array([(1, 2), (3, 4)], dtype=[('c', '<i8'), ('d', '<i8')])


In [193]:
%%timeit
concat_recarrays(arr1, arr2).a

25.8 µs ± 1.61 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [206]:
arr2 = np.array([[3, 2], [3, 2]])


In [213]:
f = arr2.astype([("a", "<f8"), ("b", "<f8")]) #.view(np.recarray)

In [265]:
f

rec.array([[(1.,), (2.,), (3.,), (4.,)],
           [(5.,), (6.,), (7.,), (8.,)]],
          dtype=[('a', '<f8')])

In [241]:
arr2 = np.array([[1, 2, 3, 4], [5,6,7,8]])
f = arr2.astype([('a', '<f8')], copy=False).view(np.recarray)

In [220]:
arr2.astype(dtype=["a", "b"])

TypeError: Field elements must be 2- or 3-tuples, got ''a''

In [230]:
from talib import SMA

In [261]:
sma = SMA(f.a, 2)

Exception: input array has wrong dimensions

In [239]:
sma = sma.astype([('sma2', '<f8')]).view(np.recarray)

In [240]:
sma

rec.array([(nan,), (1.5,), (2.5,), (3.5,)],
          dtype=[('sma2', '<f8')])

In [249]:
arr2[] arr2.reshape(-1, 2)[:, 0].astype([('sma2', '<f8')]).view(np.recarray)

rec.array([(1.,), (3.,), (5.,), (7.,)],
          dtype=[('sma2', '<f8')])

In [256]:
arr3 = arr2.reshape(-1, 2)

In [254]:
arr3[:,0] = arr3[:, 0].astype([('sma2', '<f8')])

In [257]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [260]:
import numpy as np

np.core.records.fromrecords(,
names='col1,col2,col3')

rec.array([(1, 2), (3, 4), (5, 6), (7, 8)],
          dtype=[('col1', '<i8'), ('col2', '<i8')])

In [274]:
import numpy as np
from numpy.lib.recfunctions import merge_arrays
dt1 = [('foo', int), ('bar', float)]
dt2 = [('foobar', int), ('barfoo', float)]
aa = np.ones(6, dtype=dt1).view(np.recarray)
bb = np.zeros(6, dtype=dt2).view(np.recarray)

cc = merge_arrays((aa, bb), asrecarray=True, flatten=True)
type(cc)


numpy.recarray

In [275]:
cc

rec.array([(1, 1., 0, 0.), (1, 1., 0, 0.), (1, 1., 0, 0.), (1, 1., 0, 0.),
           (1, 1., 0, 0.), (1, 1., 0, 0.)],
          dtype=[('foo', '<i8'), ('bar', '<f8'), ('foobar', '<i8'), ('barfoo', '<f8')])

In [288]:
x1=np.array([1.,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r1 = np.core.records.fromarrays([x1], names='a')
r2 = np.core.records.fromarrays([x2], names='b')
r3 = np.core.records.fromarrays([x3], names='c')


#r

In [294]:
merge_arrays([r1, r2, r3], asrecarray=True, flatten=True)

rec.array([(1., 'a', 1.1), (2., 'dd', 2. ), (3., 'xyz', 3. ),
           (4., '12', 4. )],
          dtype=[('a', '<f8'), ('b', '<U3'), ('c', '<f8')])

In [297]:
np.core.records.fromarrays([x1, x2], names='a,b')

rec.array([(1., 'a'), (2., 'dd'), (3., 'xyz'), (4., '12')],
          dtype=[('a', '<f8'), ('b', '<U3')])