In [2]:
from setup import get_settings
from trade.broker import BrokerSession
import MetaTrader5 as mt5
import pandas as pd
login_settings = get_settings("settings/demo/login.json")
trading_settings = get_settings("settings/demo/trading.json")

mt5_login_settings = login_settings["mt5_login"]

session = BrokerSession()
symbol = "EURUSD"

# Start MT5
session.start_session(mt5_login_settings)
session.enable_symbols([symbol])


In [12]:
from trade.indicators import RSIIndicator
c = session.get_candles(symbol, "M1", 14, 0, as_dataframe=True)
RSIIndicator(c.close).rsi()

time
1681365780    13.72549
1681365840    13.72549
1681365900    13.72549
1681365960    13.72549
1681366020    13.72549
1681366080    13.72549
1681366140    13.72549
1681366200    13.72549
1681366260    13.72549
1681366320    13.72549
1681366380    13.72549
1681366440    13.72549
1681366500    13.72549
1681366560    13.72549
Name: rsi, dtype: float64

In [28]:
p = np.array([20,11.25,12.35,14.5,18.45,12.75,15.35,13.05,16.10,12.20,11.65,13.25,15.30,14.85,16.15,19.05,21.45,17.55])[::-1]
RSI(p)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan, 45.83901774,
       43.115191  , 41.74833658, 54.18941067])

In [2]:
from trade.strategies import MovingAverageStrategy
mav = MovingAverageStrategy(5, 200)


In [24]:
import numpy as np
import timeit

arr = np.arange(1000000)


def append_value(arr):
    return np.append(arr, 1000000)


def concatenate_value(arr):
    return np.concatenate([arr, [1000000]])


print(timeit.timeit(lambda: append_value(arr), number=10000))
# Output: 10.277582999999988

print(timeit.timeit(lambda: concatenate_value(arr), number=10000))
# Output: 5.141081399999996


11.846058800000037
11.345299699999941


In [25]:
%%timeit
np.append(arr, 1000000)


1.19 ms ± 80.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [27]:
%%timeit
np.concatenate([arr, [1000000]])


1.18 ms ± 71.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [2]:
symbols = mt5.symbols_get()

In [9]:
b = -1
for s in symbols:
    si = mt5.symbol_info(s.name)
    a = si.volume_min
    if a != b:
        print(s.path, a, si.volume_step)
        b = a

Forex\Majors\EURUSD 0.01 0.01
Indices\Indices Spot\Major Spot Indices\AUS200 0.1 0.1
Indices\Indices Spot\Major Spot Indices\JP225 1.0 1.0
Indices\Indices Spot\Major Spot Indices\UK100 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\US2000 1.0 1.0
Indices\Indices Spot\Major Spot Indices\US30 0.1 0.1
Commodities\Metals\XAGEUR 0.01 0.01
Commodities\Energies\Energies Spot\XBRUSD 0.5 0.5
Crypto\BTCUSD 0.01 0.01
Crypto\LTCUSD 0.05 0.01
Crypto\DSHUSD 1.0 0.01
Stock CFD's\Nasdaq\AAPL.NAS 0.1 0.1
Crypto\XRPUSD 1.0 0.01
Crypto\XLMUSD 1000.0 100.0
Crypto\EOSUSD 1.0 0.01
Stock CFD's\NYSE\ETF\DBA.NYSE 0.1 0.1
Commodities\Metals\XAUAUD 0.01 0.01
Stock CFD's\NYSE\LIN.NYSE 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\CA60 1.0 1.0
Stock CFD's\Nasdaq\AMD.NAS 0.1 0.1
Crypto\ADAUSD 1.0 0.01
Stock CFD's\Nasdaq\HOOD.NAS 0.1 0.1
Crypto\XTZUSD 1.0 0.01
Crypto\BNBUSD 0.01 0.01
Indices\Indices Spot\Major Spot Indices\DE40 0.1 0.1
Indices\Indices Spot\Minor Spot Indices\MidDE50 1.0 1.0
Stock CFD's\NYSE\PANW.

In [17]:
q = 1.00000
len(str(q)) - str(q).index(".") -1

1

In [29]:
%%timeit
pd.DataFrame(a)

356 µs ± 26 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [79]:
#%%timeit
session.get_candles("EURUSD", "M1", 1)

rec.array([(1679875440, 1.07721, 1.07721, 1.07721, 1.07721, 1, 33, 0)],
          dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [3]:
session.calculate_sltp("EURUSD", "buy", 1.0000, 10, 2)


(0.999, 1.002)

In [20]:
session.calculate_sltp("EURUSD", "buy", 1.08946, 10, 2)

AccountInfo(login=51136661, trade_mode=0, leverage=500, limit_orders=200, margin_so_mode=0, trade_allowed=True, trade_expert=True, margin_mode=2, currency_digits=2, fifo_close=False, balance=420.11, credit=0.0, profit=0.0, equity=420.11, margin=0.0, margin_free=420.11, margin_level=0.0, margin_so_call=100.0, margin_so_so=50.0, margin_initial=0.0, margin_maintenance=0.0, assets=0.0, liabilities=0.0, commission_blocked=0.0, name='Reyes Vega Leonardo Moises', server='ICMarketsSC-Demo', currency='GBP', company='Raw Trading Ltd')

In [26]:
symbols = mt5.symbols_get()

In [29]:
symbols[0]

SymbolInfo(custom=False, chart_mode=0, select=True, visible=True, session_deals=0, session_buy_orders=0, session_sell_orders=0, volume=0, volumehigh=0, volumelow=0, time=1679551157, digits=5, spread=0, spread_float=True, ticks_bookdepth=10, trade_calc_mode=0, trade_mode=4, start_time=0, expiration_time=0, trade_stops_level=0, trade_freeze_level=0, trade_exemode=2, swap_mode=1, swap_rollover3days=3, margin_hedged_use_leg=False, expiration_mode=15, filling_mode=2, order_mode=127, order_gtc_mode=0, option_mode=0, option_right=0, bid=1.08952, bidhigh=1.0899, bidlow=1.08555, ask=1.08952, askhigh=1.0899, asklow=1.08561, last=0.0, lasthigh=0.0, lastlow=0.0, volume_real=0.0, volumehigh_real=0.0, volumelow_real=0.0, option_strike=0.0, point=1e-05, trade_tick_value=0.8120969968653058, trade_tick_value_profit=0.8120969968653058, trade_tick_value_loss=0.812123377783553, trade_tick_size=1e-05, trade_contract_size=100000.0, trade_accrued_interest=0.0, trade_face_value=0.0, trade_liquidity_rate=0.0, 

In [2]:
session.calculate_sltp_2("EURUSD", "sell", price=1.09133, lot_size=0.05, risk_pct=0.01, rr_ratio=2)


409.3 1.2323


(1.092360597136, 1.089268805728)

In [80]:
si = mt5.symbol_info("GBPUSD")
si2 = mt5.symbol_info_tick("GBPUSD")
t = session.get_candles("GBPUSD", "M1", 1)
t2 = session.get_ticks("GBPUSD", 5)

In [81]:
t2.ask

array([1.22351, 1.22362, 1.22362, 1.22354, 1.22354])

In [67]:
si.bid

1.22295

In [62]:
si2

Tick(time=1679702218, bid=1.22295, ask=1.22323, last=0.0, volume=0, time_msc=1679702218646, flags=6, volume_real=0.0)

In [3]:
pd.DataFrame(mt5.copy_rates_from_pos("GBPUSD", mt5.TIMEFRAME_H1, 0, 1))


time     open     high      low    close  tick_volume  spread  \
0  1679565600  1.23238  1.23256  1.23164  1.23229          737       0   

   real_volume  
0            0

In [7]:
#%%timeit
a = mt5.copy_rates_from_pos("GBPUSD", mt5.TIMEFRAME_M1, 0, 1)
b = a.view(np.recarray)


61.9 µs ± 2.33 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [26]:
a = mt5.positions_get(symbol="EURUSD")


In [28]:
a[0].symbol

'EURUSD'

In [20]:
not 100

False

In [101]:
session.create_order()
mt5.orders_get(symbol="GBPUSD")


(TradeOrder(ticket=359065032, time_setup=1679875486, time_setup_msc=1679875486789, time_done=0, time_done_msc=0, time_expiration=0, type=2, type_time=0, type_filling=2, state=1, magic=0, position_id=0, position_by_id=0, reason=0, volume_initial=0.05, volume_current=0.05, price_open=1.18674, sl=0.0, tp=0.0, price_current=1.22426, price_stoplimit=0.0, symbol='GBPUSD', comment='', external_id=''),)

In [5]:
from enum import Enum
import MetaTrader5 as mt5
class TimeFrames(Enum):
    M1 = mt5.TIMEFRAME_M1
    M2 = mt5.TIMEFRAME_M2
    M3 = mt5.TIMEFRAME_M3
    M4 = mt5.TIMEFRAME_M4
    M5 = mt5.TIMEFRAME_M5
    M6 = mt5.TIMEFRAME_M6
    M10 = mt5.TIMEFRAME_M10
    M12 = mt5.TIMEFRAME_M12
    M15 = mt5.TIMEFRAME_M15
    M20 = mt5.TIMEFRAME_M20
    M30 = mt5.TIMEFRAME_M30
    H1 = mt5.TIMEFRAME_H1
    H2 = mt5.TIMEFRAME_H2
    H3 = mt5.TIMEFRAME_H3
    H4 = mt5.TIMEFRAME_H4
    H6 = mt5.TIMEFRAME_H6
    H8 = mt5.TIMEFRAME_H8
    H12 = mt5.TIMEFRAME_H12
    D1 = mt5.TIMEFRAME_D1
    W1 = mt5.TIMEFRAME_W1
    MN1 = mt5.TIMEFRAME_MN1


In [9]:
TimeFrames._member_names_


['M1',
 'M2',
 'M3',
 'M4',
 'M5',
 'M6',
 'M10',
 'M12',
 'M15',
 'M20',
 'M30',
 'H1',
 'H2',
 'H3',
 'H4',
 'H6',
 'H8',
 'H12',
 'D1',
 'W1',
 'MN1']

In [18]:
TimeFrames.D1.name

'D1'

In [17]:
A._member_names_

[]

In [44]:
mt5.symbols_get("BCH")[0].name

'BCHUSD'

In [59]:
mt5.symbol_select("USDTRY", True)

True

In [21]:
import numpy as np

o = np.arange(5)

In [12]:
d = np.diff(o)

In [14]:
d[d > 0].sum()

0

In [21]:
a = np.ones(3)
np.append(a, np.array([]))
np.recarray

array([1., 1., 1.])

In [23]:
np.s_[:2:3]

slice(None, 2, 3)

In [32]:
np.diff(o, append=10)

array([1, 1, 1, 1, 6])

In [29]:
a = np.array([[1,]], dtype=("c", "<f8"))
a = a.view(np.recarray)

ValueError: mismatch in size of old and new data-descriptor

In [33]:
c = session.get_candles(symbol, "M1", 3)
d = session.get_candles(symbol, "M1", 1)


In [37]:
e = np.append(c, d)

In [41]:
np.delete(e, np.s_[:2], axis=0).view(np.recarray)


rec.array([(1681360740, 1.09974, 1.0999, 1.09974, 1.0999, 10, 0, 0),
           (1681360740, 1.09974, 1.0999, 1.09974, 1.0999, 10, 0, 0)],
          dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])

In [42]:
e

array([(1681360620, 1.09986, 1.09999, 1.09986, 1.09989, 52, 0, 0),
       (1681360680, 1.0999 , 1.0999 , 1.09972, 1.09975, 70, 0, 0),
       (1681360740, 1.09974, 1.0999 , 1.09974, 1.0999 , 10, 0, 0),
       (1681360740, 1.09974, 1.0999 , 1.09974, 1.0999 , 10, 0, 0)],
      dtype=[('time', '<i8'), ('open', '<f8'), ('high', '<f8'), ('low', '<f8'), ('close', '<f8'), ('tick_volume', '<u8'), ('spread', '<i4'), ('real_volume', '<u8')])